### ISSUE TITLE
stats?

### ISSUE THREAD

**Issue by paulirish** [dmolsen/Detector#13]
Do you have any stats on what properties are tested with Detector? It'd be helpful for a few projects that are currently underway..

cc @igrigorik

**Comment by dmolsen** [comment]
Can you clarify what you mean by "stats"? A list of the features it is currently testing or a dump of browser profiles?

**Comment by dmolsen** [comment]
btw, i'm running on empty (lots of traveling past few days) so if my response makes no sense i apologize. just didn't want to make you wait too long ;)

**Comment by dmolsen** [comment]
_bump_

**Comment by dmolsen** [comment]
FYI... just guessing at this but this doc is still (unfortunately) relevant when it comes to features for detector. I hope to get back to the project in January.

https://docs.google.com/spreadsheet/ccc?key=0AntZUVoCEOyYdFRpUjZOWUZyaWxoSTlLLW1XVHVldHc

closing this issue

/cc @igrigorik

**Comment by paulirish** [comment]
I mean basically what people are checking for on the serverside. So for examples in the [using Detector guide](https://github.com/dmolsen/Detector/wiki/Adding-&-Using-Detector-With-Your-Application)'s first example, 1 point each for SVG and Canvas.

I would imagine these properties are different than the most frequently checked on clientside.
