### ISSUE TITLE
OS and OS version separation

### ISSUE THREAD

**Issue by kjfranke** [dmolsen/Detector#16]
On Windows 7 I noticed the OS and OS version are not separate.

Using Detector 0.8.5

$ua->os = Windows 7
$ua->osVersion = 
$ua->osFull = Windows 7

I have not checked if the same happened on other OS's

**Comment by dmolsen** [comment]
This is actually an issue in the underlying `ua-parser` library. I've suggested a fix for it but never got anywhere with it being accepted. Sorry.
