### ISSUE TITLE
Detecting JS support

### ISSUE THREAD

**Issue by CMCDragonkai** [dmolsen/Detector#22]
What would be a good way to detect whether the browser runs javascript? I know of course the modernizr won't run at all if JS was disabled, but does the server side library have a function to let me know whether it received data from modernizr?

**Comment by dmolsen** [comment]
Yes. If there is no JS there is a meta refresh tag that runs and sets a request var called `nojs` to true. Something similar happens if cookies aren't supported.

**Comment by CMCDragonkai** [comment]
Does this happen on the first page load, or on the second page load? Because if my server side can detect it on the first page load (before output is sent), that would be great!
