### ISSUE TITLE
Critical: WSOD in IE10 and IE11

### ISSUE THREAD

**Issue by carpusmedia** [dmolsen/Detector#32]
Hello,

detector.dmolsen.com and our site using Detector results in a WSOD in IE10 and IE11, thus making this software unusable.

Anyone found a fix for this?

Thank you,
Chris

**Comment by afryer** [comment]
Needs latest modernizer v3 which is not released via site but is available
on github

https://github.com/Modernizr/Modernizr

Was gonna do a pull request but unsure on status of project

**Comment by carpusmedia** [comment]
Ok, thanks for the heads up <strong>afryer</strong>. Gonna try it and report back.

Thank you,
Chris

**Comment by carpusmedia** [comment]
Upgrading the Modernizr library to the latest version (2.8.3) solved the problem in both IE10 and IE11.

<ol>
<li>Download the latest Modernizr version. Open up <code>lib/modernizr/modernizr.2.5.2.min.custom.js</code> and <code>lib/modernizr/modernizr.2.5.2.min.no-tests.js</code>and use the links at the top of the documents to grab the latest Modernizr package for each build.</li>
<li>Configure Detector to use the new Modernizr scripts. Open up <code>lib/config.ini</code> and change the <code>uaFeaturesMaxJS</code> and <code>uaFeaturesMinJS</code> to point to the new Modernizr scripts.</li>
</ol>

Thank you,
Chris
