### ISSUE TITLE
Notice: Undefined index: {my cookie}-pr

### ISSUE THREAD

**Issue by greenSkin** [dmolsen/Detector#7]
Notice: Undefined index: {my cookie}-pr in Detector::build() (line 119 of /Detector/Detector.php).

Replace {my cookie} with a cookie hash.

I'm running PHP 5.3.8.

**Comment by dmolsen** [comment]
Just wanted to let you know i've seen all these and will probably address them tomorrow. Thanks much!

**Comment by dmolsen** [comment]
fixed in v0.5.1. thanks.
