### ISSUE TITLE
Problem with perrequest

### ISSUE THREAD

**Issue by b4z81** [dmolsen/Detector#8]
Hi,
first of all, thank you so muck for your great job..
i m testing the perrequest including the features.js.php into my head, what i get it s just a print of all the js code requried (modernizr, dpi and screenattributes). what s wrong?

thank you in advance

**Comment by dmolsen** [comment]
Can you copy out the code you're seeing into a Gist or a comment here? I think I understand what you're saying but I want to be sure we're on the same page. Thank you.

**Comment by b4z81** [comment]
Hi,
the gist: https://gist.github.com/2628930
i include the features.js.php inside the functions.php (the functions of the wordpress theme) and then opening the homepage i get the home.html code..

**Comment by dmolsen** [comment]
features.js.php needs to be called from a JavaScript tag like so:

<script type="text/javascript" src="path/to/public/dir/features.js.php"></script>


Alternatively, you could modify your features.js.php file that you're already requiring so it outputs the script tags as well as the JS code. 

I'll double check the docs to make sure I've written down the instructions correctly. I've been known to skip a step or two sometimes ;)

Hope this helps.

**Comment by b4z81** [comment]
omg! thanks a lot! could i ask you another question? when i include just detector.php and then i print the dump of $ua on Chrome i can find also the screenattributes object but not on FF or IE..

**Comment by tyssen** [comment]
I don't know if it's just me, but I couldn't get `features.js.php` to set cookies until I added `?dynamic=true` at the end.
